dist: trusty

language: go

notifications:
  email: false

addons:
  sonarcloud:
    organization: "negapedia"
    token:
      secure: "NnXy9Jgzfgxrogu9LInWQsWx8E8LcsvO64/Xq9XJkibKmGiBHgVMT5mkeAyhgiPccqdixtGnFiJ6LP1tpr96S7JPXbJHLzVLqyEU5gysI1hN2upvfKtQmUCUScd+JKMvmvtWYMxDKrM4Q+JUe1uOwgs3qPhBRI5zqGCKMtd3mwzOXtLsyEkia3KSCXYzmpuecPK/BLn7+GFJqEF5Epnqhe+ZFbLb+jN42qLNKO1bju/7pwf2ygOBRauTdA86glyHtfWksyFV+TjVw9TYwOguL6wDZdMk7aSsg/Pn85daf8hf477iYIGunvj6UTY2WbD3nbfJKmMrAPEDcpVM8REp6EZPPANQNLnGK6tEjavYo6qUN9q3wjDv66aTrVqnHGkt5T/qKHxUBF3HlUH74N0SgC/Xi9caXJEy8LtdV3bfv3nq7I+rp+vrsUJ1jI2e/rFd8zIa0vWd1i92PPUXQ5GnG592MjiDAqA6npmHeA0Q2ZxtwrssSJiNaVKkpgyzhFqlbtd98/Mz13knKPzkqPXPi0MG1pQr9KHrr7oE5n4mYXBF9OdwxPjuZMPSjvmB46dHPSEHTMOVAHC2nVQRamaYLF7PnHYb69eU4u2bhBzw20MPQbrIJT6uU3bCdyxhobeuJ+gu3A7nC3y/rXtklQshbbz8bapGQWzOQlNi6EKK8bg="

sudo: required

install: true

services:
  - docker

before_install:
  - docker pull ebonetti/golang-petsc
  - |
    docker build -t test-env -<<<'
    FROM ebonetti/golang-petsc
    WORKDIR /go/src/github.com/negapedia/wikiassignment
    RUN  set -eux; \
    go get github.com/negapedia/wikidump/...; \
    go get ./...;
    '
  - docker run -v $PWD:/go/src/github.com/negapedia/wikiassignment -d --name test-env test-env sleep 600

script:
  - docker exec test-env go test -race ./... -coverprofile=coverage.out
  - sonar-scanner -Dsonar.projectKey=negapedia_wikiassignment -Dsonar.projectName=wikiassignment -Dsonar.projectVersion=1.0 -Dsonar.sources=. -Dsonar.tests=. -Dsonar.test.inclusions=**/*_test.go -Dsonar.go.coverage.reportPaths=coverage.out

after_script:
- docker rm -f test-env